# Generated by Django 4.2.16 on 2024-11-06 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_level_referral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
